### PR TITLE
Add commits from the 47Y fork and initial path Foundry 0.8.X

### PR DESCRIPTION
**Pull request by p4535992**

### CODE REVIEW

**Comment by p4535992** [comment]
Add some initial patch for foundryvtt 0.8.6 and npm for better build the project in the future

**Comment by paullessing** [comment]
Hey @VanirDev, this looks like a good patch. Any thoughts on integrating it into VE?

**Comment by RavenknightDM** [comment]
Did you guys get the mod working again? If so, can I use it without the pull request being admitted?

**Comment by p4535992** [comment]
hi @VanirDev,  I wanted to ask you if you could make me a contributor to your project so that I could manage the issues and implement my code.
There are already over 1000 foundryvtt addons I wanted to avoid creating another one which is an updated version of your idea.

**Comment by Gorvaine** [comment]
I think it's fork time... This is abandoned

**Comment by VanirDev** [comment]
> 
> 
> hi @VanirDev, I wanted to ask you if you could make me a contributor to your project so that I could manage the issues and implement my code.
> There are already over 1000 foundryvtt addons I wanted to avoid creating another one which is an updated version of your idea.

Hi, sorry for abandoning this and thank you for all the work you've been putting into maintaining it. I'll be adding you as a contributor and merging in the PR

**Comment by p4535992** [comment]
Ty @VanirDev ^^

**Comment by p4535992** [comment]
At this point I also try to ask for the ownership of the module so as to update it also on FoundryVTT, if it is not a problem for you!

**Comment by VanirDev** [comment]
I've spoken with mattexdee, and I've given permission for the module to be transferred to you. I would still like to keep my name in the manifest alongside yours if that's okay!

**Comment by p4535992** [comment]
Sure indeed I left you as the first in the list of authors !!!
`"author": "Vanir#0001 (discord), 47Y, p4535992",`
 if you want you can also manage the module on foundry no problem.

**Pull request merged**
